server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - JwtAuthentication
      routes:
        # OpenAPI Documentation routes
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/swagger-ui/**, /webjars/**, /v3/api-docs/swagger-config, /v3/api-docs/gateway
          filters:
            - StripPrefix=0

        # Service OpenAPI routes
        - id: product-service-docs
          uri: lb://product-service
          predicates:
            - Path=/v3/api-docs/product-service/**
          filters:
            - RewritePath=/v3/api-docs/product-service/(?<segment>.*), /v3/api-docs/$\{segment}

        - id: cart-service-docs
          uri: lb://cart-service
          predicates:
            - Path=/v3/api-docs/cart-service/**
          filters:
            - RewritePath=/v3/api-docs/cart-service/(?<segment>.*), /v3/api-docs/$\{segment}

        - id: order-service-docs
          uri: lb://order-service
          predicates:
            - Path=/v3/api-docs/order-service/**
          filters:
            - RewritePath=/v3/api-docs/order-service/(?<segment>.*), /v3/api-docs/$\{segment}

        - id: security-service-docs
          uri: lb://security-service
          predicates:
            - Path=/v3/api-docs/security-service/**
          filters:
            - RewritePath=/v3/api-docs/security-service/(?<segment>.*), /v3/api-docs/$\{segment}

        - id: vendor-service-docs
          uri: lb://vendor-service
          predicates:
            - Path=/v3/api-docs/vendor-service/**
          filters:
            - RewritePath=/v3/api-docs/vendor-service/(?<segment>.*), /v3/api-docs/$\{segment}

        - id: notification-service-docs
          uri: lb://notification-service
          predicates:
            - Path=/v3/api-docs/notification-service/**
          filters:
            - RewritePath=/v3/api-docs/notification-service/(?<segment>.*), /v3/api-docs/$\{segment}

        # Regular service routes
        - id: auth-service
          uri: lb://security-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=0

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=0

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=0

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**
          filters:
            - StripPrefix=0

        - id: vendor-service
          uri: lb://vendor-service
          predicates:
            - Path=/vendors/**
          filters:
            - StripPrefix=0

# Exclude paths from JWT authentication
jwt:
  excluded-paths:
    - /auth/**
    - /swagger-ui/**
    - /swagger-ui.html
    - /v3/api-docs/**
    - /*/v3/api-docs/**
    - /webjars/**
    - /actuator/**

# OpenAPI Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    configUrl: /v3/api-docs/swagger-config
    urls-primary-name: API Gateway
    disable-swagger-default-url: true
    display-request-duration: true
    show-common-extensions: true
    syntax-highlight:
      activated: true
    use-root-path: true
  api-docs:
    enabled: true
    path: /v3/api-docs
  cache:
    disabled: true
  group-configs:
    - group: all
      paths-to-match: /**
  show-actuator: true
  enable-spring-security: false
  enable-data-rest: false
  writer-with-default-pretty-printer: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30

resilience4j:
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
  retry:
    instances:
      default:
        maxAttempts: 3
        waitDuration: 1s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    com.nextgen.shopping.gateway: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 